version: "3.4"

services:
  site:
    build:
      context: ./
      dockerfile: ./provision/site_dockerfile
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - 8001:8001
    restart: unless-stopped
    volumes:
      - .:/app/src
    environment:
      - DB_NAME=problem_server_db
      - DB_USER=problem_user
      - DB_PSW=123456
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - celery

  db:
    image: postgres:10.0-alpine
    ports:
      - 8002:5432
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./provision/db_scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=problem_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=problem_server_db

  celery:
    build:
      context: .
      dockerfile: ./provision/site_dockerfile
    command: celery worker --app=problem_server --loglevel=info
    restart: unless-stopped
    environment:
      - DB_NAME=problem_server_db
      - DB_USER=problem_user
      - DB_PSW=123456
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:5-alpine

volumes:
  postgres_data:
